#! /bin/bash
read -p 'Seed Class Name(press enter if none): ' seed
read -p 'Add options(press enter if none): ' options

if [ ! -z $seed ];
then
	seed_class="--class=${seed}"
else 
	seed_class=''
fi

php artisan db:seed $seed_class $options