FROM hxhroniegss/laravel5
LABEL maintainer="Ronie Vincent Horca <ronievincent.gss@gmail.com>"
# Changed directory to laravel

WORKDIR /var/www/html/src/laravel/public
RUN chgrp -R www-data /var/www/html/src/laravel